/** @jsxImportSource ../../src */

import type {
  CustomElementProps,
  CustomElementTag,
  DOMEvent,
  DOMEventHandler,
  DOMEventHandlerProp,
  DOMEventListenerObject,
  DOMEventMapFor,
  DOMProps,
  DOMPropsBase,
  DOMRenderer,
  DOMRuntimeOptions,
  ElementInstance,
  ElementProps,
  ElementTag,
  ForProps,
  HTMLProps,
  IntrinsicElements,
  JSXRenderable,
  MathMLProps,
  Model,
  ModelAction,
  ModelContext,
  ModelFactory,
  ModelHandle,
  ModelOptions,
  ModelReadable,
  ModelSetup,
  ModelValue,
  MountEffects,
  PlatformProps,
  PortalProps,
  Ref,
  RefAttributes,
  RefObject,
  ShowProps,
  SVGProps,
  StyleObject,
  StyleValue,
  SwitchCase,
  SwitchProps,
  UseEffectFn,
} from "../../src";

/** Compile-time inventory for every type-only public export. */
export type PublicDOMTypes = [
  ForProps<number>,
  PortalProps,
  ShowProps<number>,
  SwitchCase<number>,
  SwitchProps<number>,
  UseEffectFn,
  DOMRenderer,
  DOMRuntimeOptions,
  MountEffects,
  CustomElementProps,
  CustomElementTag,
  DOMEvent<HTMLButtonElement>,
  DOMEventHandler<HTMLButtonElement>,
  DOMEventHandlerProp<HTMLButtonElement>,
  DOMEventListenerObject<HTMLButtonElement>,
  DOMEventMapFor<HTMLButtonElement>,
  DOMProps<HTMLButtonElement>,
  DOMPropsBase,
  ElementInstance<"button">,
  ElementProps<"button">,
  ElementTag,
  HTMLProps<HTMLButtonElement>,
  IntrinsicElements,
  JSXRenderable,
  MathMLProps,
  PlatformProps,
  Ref<HTMLButtonElement>,
  RefAttributes<HTMLButtonElement>,
  RefObject<HTMLButtonElement>,
  SVGProps,
  StyleObject,
  StyleValue,
  Model<{ value: ModelReadable<number> }>,
  ModelAction,
  ModelContext,
  ModelFactory<[], { value: ModelReadable<number> }>,
  ModelHandle,
  ModelOptions,
  ModelReadable<number>,
  ModelSetup<[], { value: ModelReadable<number> }>,
  ModelValue<ModelReadable<number>>,
];

// These assignments verify useful relationships, beyond the import inventory.
const buttonProps: ElementProps<"button"> = {
  onClick(event) {
    const target: HTMLButtonElement = event.currentTarget;
    void target;
  },
};
const button: ElementInstance<"button"> = document.createElement("button");
const content: JSXRenderable = <button {...buttonProps}>ok</button>;
const modelValue: ModelValue<ModelReadable<number>> = 1;
void [button, content, modelValue];
