const HTML_TAGS = {
  a: true,
  abbr: true,
  address: true,
  area: true,
  article: true,
  aside: true,
  audio: true,
  b: true,
  base: true,
  bdi: true,
  bdo: true,
  blockquote: true,
  body: true,
  br: true,
  button: true,
  canvas: true,
  caption: true,
  cite: true,
  code: true,
  col: true,
  colgroup: true,
  data: true,
  datalist: true,
  dd: true,
  del: true,
  details: true,
  dfn: true,
  dialog: true,
  div: true,
  dl: true,
  dt: true,
  em: true,
  embed: true,
  fieldset: true,
  figcaption: true,
  figure: true,
  footer: true,
  form: true,
  h1: true,
  h2: true,
  h3: true,
  h4: true,
  h5: true,
  h6: true,
  head: true,
  header: true,
  hgroup: true,
  hr: true,
  html: true,
  i: true,
  iframe: true,
  img: true,
  input: true,
  ins: true,
  kbd: true,
  label: true,
  legend: true,
  li: true,
  link: true,
  main: true,
  map: true,
  mark: true,
  menu: true,
  meta: true,
  meter: true,
  nav: true,
  noscript: true,
  object: true,
  ol: true,
  optgroup: true,
  option: true,
  output: true,
  p: true,
  param: true,
  picture: true,
  pre: true,
  progress: true,
  q: true,
  rb: true,
  rp: true,
  rt: true,
  rtc: true,
  ruby: true,
  s: true,
  samp: true,
  script: true,
  search: true,
  section: true,
  select: true,
  slot: true,
  small: true,
  source: true,
  span: true,
  strong: true,
  style: true,
  sub: true,
  summary: true,
  sup: true,
  table: true,
  tbody: true,
  td: true,
  template: true,
  textarea: true,
  tfoot: true,
  th: true,
  thead: true,
  time: true,
  title: true,
  tr: true,
  track: true,
  u: true,
  ul: true,
  var: true,
  video: true,
  wbr: true,
} as const;

const SVG_TAGS = {
  a: true,
  animate: true,
  animateMotion: true,
  animateTransform: true,
  circle: true,
  clipPath: true,
  defs: true,
  desc: true,
  ellipse: true,
  feBlend: true,
  feColorMatrix: true,
  feComponentTransfer: true,
  feComposite: true,
  feConvolveMatrix: true,
  feDiffuseLighting: true,
  feDisplacementMap: true,
  feDistantLight: true,
  feDropShadow: true,
  feFlood: true,
  feFuncA: true,
  feFuncB: true,
  feFuncG: true,
  feFuncR: true,
  feGaussianBlur: true,
  feImage: true,
  feMerge: true,
  feMergeNode: true,
  feMorphology: true,
  feOffset: true,
  fePointLight: true,
  feSpecularLighting: true,
  feSpotLight: true,
  feTile: true,
  feTurbulence: true,
  filter: true,
  font: true,
  "font-face": true,
  foreignObject: true,
  g: true,
  glyph: true,
  glyphRef: true,
  hkern: true,
  image: true,
  line: true,
  linearGradient: true,
  marker: true,
  mask: true,
  metadata: true,
  "missing-glyph": true,
  mpath: true,
  path: true,
  pattern: true,
  polygon: true,
  polyline: true,
  radialGradient: true,
  rect: true,
  script: true,
  set: true,
  stop: true,
  style: true,
  svg: true,
  switch: true,
  symbol: true,
  text: true,
  textPath: true,
  title: true,
  tref: true,
  tspan: true,
  use: true,
  view: true,
  vkern: true,
} as const;

const VOID_TAGS = {
  area: true,
  base: true,
  br: true,
  col: true,
  embed: true,
  hr: true,
  img: true,
  input: true,
  link: true,
  meta: true,
  param: true,
  source: true,
  track: true,
  wbr: true,
} as const;

type HTMLTag = keyof typeof HTML_TAGS;
type SVGTag = keyof typeof SVG_TAGS;
type VoidTag = keyof typeof VOID_TAGS;

function hasTag<T extends HTMLTag | SVGTag | VoidTag>(
  tag: T,
  type: "html" | "svg" | "void" = "html"
): boolean {
  switch (type) {
    case "html":
      return !!HTML_TAGS[tag as HTMLTag];
    case "svg":
      return !!SVG_TAGS[tag as SVGTag];
    case "void":
      return !!VOID_TAGS[tag as VoidTag];
    default:
      return false;
  }
}

const isHTMLTag = (tag: HTMLTag): boolean => hasTag(tag, "html");
const isSVGTag = (tag: SVGTag): boolean => hasTag(tag, "svg");
const isVoidTag = (tag: VoidTag): boolean => hasTag(tag, "void");

export {
  isHTMLTag,
  isSVGTag,
  isVoidTag,
  hasTag,
  HTMLTag,
  SVGTag,
  VoidTag,
};
